shim-version: v0.4.2@sha256:d65f769e37bbe86ffaeef42120c29c4b9de33415fcd7588a9ef7a64f609aa2a3
cvm-version: 0.6.9
cpus: 8
memory: 65536

containers:
  - name: "inference-verifier"
    image: "ghcr.io/benhagag10/inference-verification-tee:v0.7.5@sha256:fdc860ff31672504743e785b6e4facc02c87cdae7ec5a7928a6b83782c1b72e0"
    runtime: nvidia
    gpus: all
    secrets:
      - HF_TOKEN

shim:
  listen-port: 443
  upstream-port: 8080
  paths:
    - /verify
    - /verify-stream
    - /query-and-verify
    - /query-and-verify-stream
    - /health
    - /config
    - /ui
